

export const manhwaList = [
  {
    id: "MMTB1",
    title: "Maybe Meant to be",
    chapter: "133",
    maxChapter: 133,
    status: "Fini",
    link: "",
    lastReadCount: "40",
    lastRead: "04/02/2026",
    description: "2 trentenaires (anciens amis d'enfance) qui décident de se marier sur un coup de tête lors",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/1/262022l.jpg"
  },
  {
    id: "MBGOTLT2",
    title: "My bias get on the last train",
    chapter: "70",
    maxChapter: 70,
    status: "En Cours",
    link: "https://roliascan.com/manga/my-bias-gets-on-the-last-train/chapter-",
    lastReadCount: "1",
    lastRead: "15/03/2026",
    description: "2 personnes prennent le dernier train, l'un étant fan du groupe de musique de l'autre sans savoir que c'est elle. Ils vont alors commence à discuter et apprendre à se connaître grâce au groupe de musique",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/2/318971l.jpg"
  },
  {
    id: "JF3",
    title: "Just Friends",
    chapter: "67",
    maxChapter: 67,
    status: "Hiatus",
    link: "https://templetoons.com/comic/childhood-friend-complex/chapter-",
    lastReadCount: "10",
    lastRead: "06/03/2026",
    description: "2 amis d'enfance étudiants vont se rendre compte qu'ils ont des sentiment l'un pour l'autre",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/2/301737l.jpg"
  },
  {
    id: "J2W4",
    title: "Just 2 Week",
    chapter: "69",
    maxChapter: 69,
    status: "Fini",
    link: "https://mangabuddy.com/two-weeks-and-counting/chapter-",
    lastReadCount: "32",
    lastRead: "12/02/2026",
    description: "1 étudiants decide de receuillir une fugueuse qui attandais devant chez lui pour 2 semaines, des sentiments vont alors naître des 2 côtés",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/1/281966l.jpg"
  },
  {
    id: "TGED5",
    title: "The Greatest Estate Developer",
    chapter: "222",
    maxChapter: 222,
    status: "Fini",
    link: "https://asuracomic.net/series/the-greatest-estate-developer-87e4e996/chapter/",
    lastReadCount: "17",
    lastRead: "27/02/2026",
    description: "Le mec le plus moche du monde décide de devenir un constructeur de génie (il se tappe la reine)",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/5/274459l.jpg"
  },
  {
    id: "WABHDL6",
    title: "What a Bountiful Harvest, Demon Lord!",
    chapter: "57",
    maxChapter: 58,
    status: "En Cours",
    link: "https://asuracomic.net/series/what-a-bountiful-harvest-demon-lord-776089ce/chapter/",
    lastReadCount: "7",
    lastRead: "09/03/2026",
    description: "Comme au dessus mais là c'est le roi demon et c'est de l'agriculture",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/4/334141l.jpg"
  },
  {
    id: "JCL7",
    title: "Job Change Log",
    chapter: "54",
    maxChapter: 54,
    status: "Hiatus",
    link: "https://roliascan.com/manga/job-switch-log/chapter-",
    lastReadCount: "0",
    lastRead: "16/03/2026",
    description: "Max découvre sur le pc de Joy qu'elle chercher un nouvel emploi et ensemble ils décident de faire un projet web pour améliorer le portfolio",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/321592l.jpg"
  },
  {
    id: "MWIF1YA8",
    title: "My wife is from 1000 year ago",
    chapter: "28",
    maxChapter: 456,
    status: "En Cours",
    link: "https://manhuaus.com/manga/my-wife-is-from-thousand-years-ago/chapter-",
    lastReadCount: "",
    lastRead: "",
    description: "1 chinoise des années 800 se retrouve dans la chine moderne",
    nsfw: 0,
    cover: "https://www.nautiljon.com/images/manga/00/75/wo_jia_lao_po_lai_zi_yi_qian_nian_qian_24157.webp?0"
  },
  {
    id: "MIB9",
    title: "Mia is back",
    chapter: "34",
    maxChapter: 34,
    status: "En Cours",
    link: "https://kingofshojo.com/mia-is-back-chapter-",
    lastReadCount: "0",
    lastRead: "16/03/2026",
    description: "La meuf du prota a disparu du jour au lendemain et 5 ans elle réapparaît sans crier gare",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/2/334162l.jpg"
  },
  {
    id: "SL10",
    title: "Solo Leveling",
    chapter: "200",
    maxChapter: 200,
    status: "Fini",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/222295l.jpg"
  },
  {
    id: "SOS11",
    title: "Skool of Street",
    chapter: "0",
    maxChapter: 77,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/302968l.jpg"
  },
  {
    id: "BTC12",
    title: "Back to Chanbi",
    chapter: "0",
    maxChapter: 95,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/314363l.jpg"
  },
  {
    id: "R113",
    title: "Romance 101",
    chapter: "0",
    maxChapter: 158,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/4/281570l.jpg"
  },
  {
    id: "WCNKL14",
    title: "Webtoon Character Na Kang Lim",
    chapter: "0",
    maxChapter: 172,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/1/292948l.jpg"
  },
  {
    id: "SSCH15",
    title: "SSS Suicide class hunter",
    chapter: "151",
    maxChapter: 151,
    status: "Hiatus",
    link: "https://poseidon-scans.co/serie/sss-class-suicide-hunter/chapter/",
    lastReadCount: "2",
    lastRead: "14/03/2026",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/1/260761l.jpg"
  },
  {
    id: "SOB16",
    title: "seasons of blossom",
    chapter: "0",
    maxChapter: 135,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/257932l.jpg"
  },
  {
    id: "LM17",
    title: "Lucky Mia!",
    chapter: "3",
    maxChapter: 14,
    status: "En Cours",
    link: "https://divatoon.com/series/lucky-mia/chapter-",
    lastReadCount: "10",
    lastRead: "06/03/2026",
    description: "1 mec ultra malchanceux rencontre une meuf ultra chanceuse",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/341878l.jpg"
  },
  {
    id: "C18",
    title: "Circles",
    chapter: "215",
    maxChapter: 215,
    status: "Fini",
    link: "https://hentaizone.xyz/manga/circles/chapitre-",
    lastReadCount: "11",
    lastRead: "05/03/2026",
    description: "",
    nsfw: 1,
    cover: "https://i0.wp.com/cdn.imgchest.com/files/7bwckva66r7.jpg?w=648&ssl=1"
  },
  {
    id: "LQ19",
    title: "Love quest",
    chapter: "7",
    maxChapter: 7,
    status: "En Cours",
    link: "https://omegascans.org/series/love-quest/chapter-",
    lastReadCount: "1",
    lastRead: "15/03/2026",
    description: "",
    nsfw: 1,
    cover: "https://omegascans.org/_next/image?url=https%3A%2F%2Fmedia.omegascans.org%2Ffile%2FzFSsXt%2Fj47x7h4ut4hhkwxabh4zvy9f.webp&w=640&q=75"
  },
  {
    id: "LN20",
    title: "Landlady noona",
    chapter: "0",
    maxChapter: 156,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://omegascans.org/_next/image?url=https%3A%2F%2Fmedia.omegascans.org%2Ffile%2FzFSsXt%2Fefe5ol9j6d8lpmpty40c21mo.webp&w=640&q=75"
  },
  {
    id: "TO21",
    title: "Touch On",
    chapter: "0",
    maxChapter: 109,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://i0.wp.com/manhwa18.net/storage/images/raw/aa761af3-cc6e-4b65-a675-5ee39508762a.jpg"
  },
  {
    id: "NMNL22",
    title: "No More no less",
    chapter: "0",
    maxChapter: 51,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://static.tnlycdn.com/2022/04/No-More-No-Less-manhwa-224x320.jpg"
  },
  {
    id: "RR23",
    title: "Relationship reversal",
    chapter: "0",
    maxChapter: 99,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://omegascans.org/_next/image?url=https%3A%2F%2Fmedia.omegascans.org%2Ffile%2FzFSsXt%2Fg0zkk077e9v933sf3x9dlk26.webp&w=640&q=75"
  },
  {
    id: "FTWT24",
    title: "Fucked the world tree",
    chapter: "55",
    maxChapter: 55,
    status: "Fini",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://omegascans.org/_next/image?url=https%3A%2F%2Fmedia.omegascans.org%2Ffile%2FzFSsXt%2Fwi82miz2maxtbn8etnm3l7zt.webp&w=640&q=75"
  },
  {
    id: "LTHW25",
    title: "Learning the hard way",
    chapter: "92",
    maxChapter: 92,
    status: "Fini",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://x-manga.org/wp-content/uploads/2022/06/learning.webp"
  },
  {
    id: "AID26",
    title: "As if daughter",
    chapter: "50",
    maxChapter: 50,
    status: "Fini",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://myspacecat.pictures/manhwa/as-if-daughter/cover.png?v=1"
  },
  {
    id: "CAN27",
    title: "Close as Neighbors",
    chapter: "52",
    maxChapter: 52,
    status: "Fini",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://min.manhwa18.net/chapters/manga/covers/b4db1fc7-bb7f-49f1-a880-2f100e0087ae.jpg"
  },
  {
    id: "NH&SF28",
    title: "Nan Hao & Shang Feng",
    chapter: "",
    status: "En Cours",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/1/254654l.jpg"
  },
  {
    id: "WTG?29",
    title: "Who's that girl ?",
    chapter: "53",
    maxChapter: 53,
    status: "En Cours",
    link: "https://roliascan.com/manga/whos-that-girl/chapter-",
    lastReadCount: "0",
    lastRead: "16/03/2026",
    description: "Ranma 1/2 mais où le mec/meuf veut devenir une Idole",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/3/332494l.jpg"
  },
  {
    id: "TEASG30",
    title: "the extra academy survival guide",
    chapter: "97",
    maxChapter: 97,
    status: "En Cours",
    link: "",
    lastReadCount: "1",
    lastRead: "15/03/2026",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/2/316597l.jpg"
  },
  {
    id: "TRMM31",
    title: "The Regressed mercenary's machinations",
    chapter: "0",
    maxChapter: 81,
    status: "Pas lu",
    link: "https://asuracomic.net/series/the-regressed-mercenarys-machinations-726d9cd3/chapter/",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 0,
    cover: "https://myanimelist.net/images/manga/2/327685l.jpg"
  },
  {
    id: "AOWI32",
    title: "An outsider's way in",
    chapter: "0",
    maxChapter: 97,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://t.hdporncomics.com/cover/an-outsider-s-way-in.jpg"
  },
  {
    id: "SO33",
    title: "Switch on",
    chapter: "0",
    maxChapter: 56,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://cdn.manhwature.com/hentai20.io/wp-content/uploads/2024/08/switch-on-01-193x278.jpg"
  },
  {
    id: "DL34",
    title: "Distorted love",
    chapter: "0",
    maxChapter: 8,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://pbs.twimg.com/media/GqVonoeacAAqWSR?format=jpg&name=large"
  },
  {
    id: "SF35",
    title: "Stepmother' friend",
    chapter: "0",
    maxChapter: 147,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://mangadex.org/covers/e87483f7-3099-4594-a166-d9974b205d9a/727566ff-f376-4e3a-a740-bcc348d53381.jpg"
  },
  {
    id: "SM36",
    title: "soothe me",
    chapter: "0",
    maxChapter: 60,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://www.pornhwaz.com/wp-content/uploads/2025/03/Soothe-Me-Manhwa-Latest-Chapters-Pornhwaz-175x238.webp"
  },
  {
    id: "PBGA37",
    title: "pleasure board game asmodek",
    chapter: "0",
    maxChapter: 16,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://manhwaclub.net/wp-content/uploads/2025/12/New-Pleasure-Board-Game-Asmodek.jpg"
  },
  {
    id: "SSG38",
    title: "Sex Study group",
    chapter: "0",
    maxChapter: 110,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://cdn.manhwature.com/hentai20.io/wp-content/uploads/2024/08/sextudy-group-193x278.jpg"
  },
  {
    id: "LG39",
    title: "lucky guy",
    chapter: "0",
    maxChapter: 71,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5bhmSAIjpcsM3tnktq3X8P8ax-Kd1teN3CA&s"
  },
  {
    id: "KISFYM40",
    title: "keep it secret from your mother",
    chapter: "0",
    maxChapter: 100,
    status: "Pas lu",
    link: "",
    lastReadCount: "",
    lastRead: "",
    description: "",
    nsfw: 1,
    cover: "https://www.pornhwaz.com/wp-content/uploads/2025/03/Keep-it-a-secret-from-your-mother-Manhwa-Latest-Chapters-Pornhwaz.webp"
  }
];